/**
 * Angular Version Compatibility Tests
 *
 * These tests verify that angular-cli-ghpages correctly handles the angular.json
 * structure for each Angular version. The fixture files are actual angular.json
 * files generated by `ng new` with each Angular CLI version.
 *
 * Key differences between versions:
 *
 * Angular 18-19:
 *   - builder: @angular-devkit/build-angular:application
 *   - outputPath: "dist/<project>" (string)
 *
 * Angular 20:
 *   - builder: @angular/build:application (new package!)
 *   - outputPath: MISSING (uses default dist/<project>)
 *   - index: MISSING (uses default src/index.html)
 *
 * Angular 21:
 *   - builder: @angular/build:application
 *   - outputPath: MISSING
 *   - polyfills: MISSING (zoneless by default)
 *   - test builder changed to @angular/build:unit-test
 */

import { SchematicContext, Tree } from '@angular-devkit/schematics';
import fs from 'fs';
import path from 'path';
import { ngAdd } from '../ng-add';

// Load fixture files - actual angular.json from each Angular CLI version
const fixturesDir = path.join(__dirname);
const angular18Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-18.json'), 'utf-8'));
const angular19Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-19.json'), 'utf-8'));
const angular20Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-20.json'), 'utf-8'));
const angular21Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-21.json'), 'utf-8'));

describe('Angular Version Compatibility', () => {
  /**
   * Angular 18: Standard outputPath as string
   */
  describe('Angular 18', () => {
    it('has outputPath as string "dist/ng18"', () => {
      const outputPath = angular18Config.projects.ng18.architect.build.options.outputPath;
      expect(outputPath).toBe('dist/ng18');
      expect(typeof outputPath).toBe('string');
    });

    it('uses @angular-devkit/build-angular builder', () => {
      const builder = angular18Config.projects.ng18.architect.build.builder;
      expect(builder).toBe('@angular-devkit/build-angular:application');
    });

    it('has index.html specified', () => {
      const index = angular18Config.projects.ng18.architect.build.options.index;
      expect(index).toBe('src/index.html');
    });

    it('ng add succeeds', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular18Config));

      const result = await ngAdd({ project: 'ng18' })(tree, {} as SchematicContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng18.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  /**
   * Angular 19: Same structure as Angular 18
   */
  describe('Angular 19', () => {
    it('has outputPath as string "dist/ng19"', () => {
      const outputPath = angular19Config.projects.ng19.architect.build.options.outputPath;
      expect(outputPath).toBe('dist/ng19');
      expect(typeof outputPath).toBe('string');
    });

    it('uses @angular-devkit/build-angular builder', () => {
      const builder = angular19Config.projects.ng19.architect.build.builder;
      expect(builder).toBe('@angular-devkit/build-angular:application');
    });

    it('has index.html specified', () => {
      const index = angular19Config.projects.ng19.architect.build.options.index;
      expect(index).toBe('src/index.html');
    });

    it('ng add succeeds', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular19Config));

      const result = await ngAdd({ project: 'ng19' })(tree, {} as SchematicContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng19.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  /**
   * Angular 20: Breaking change - outputPath removed!
   */
  describe('Angular 20', () => {
    it('has NO outputPath (uses default)', () => {
      const options = angular20Config.projects.ng20.architect.build.options;
      expect(options.outputPath).toBeUndefined();
    });

    it('uses NEW @angular/build builder', () => {
      const builder = angular20Config.projects.ng20.architect.build.builder;
      expect(builder).toBe('@angular/build:application');
    });

    it('has NO index property (uses default src/index.html)', () => {
      const options = angular20Config.projects.ng20.architect.build.options;
      expect(options.index).toBeUndefined();
    });

    it('still has polyfills with zone.js', () => {
      const polyfills = angular20Config.projects.ng20.architect.build.options.polyfills;
      expect(polyfills).toContain('zone.js');
    });

    it('ng add succeeds despite missing outputPath', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular20Config));

      const result = await ngAdd({ project: 'ng20' })(tree, {} as SchematicContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng20.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  /**
   * Angular 21: Even more minimal - polyfills removed (zoneless)
   */
  describe('Angular 21', () => {
    it('has NO outputPath (uses default)', () => {
      const options = angular21Config.projects.ng21.architect.build.options;
      expect(options.outputPath).toBeUndefined();
    });

    it('uses @angular/build builder', () => {
      const builder = angular21Config.projects.ng21.architect.build.builder;
      expect(builder).toBe('@angular/build:application');
    });

    it('has NO polyfills (zoneless by default)', () => {
      const options = angular21Config.projects.ng21.architect.build.options;
      expect(options.polyfills).toBeUndefined();
    });

    it('has NO index property', () => {
      const options = angular21Config.projects.ng21.architect.build.options;
      expect(options.index).toBeUndefined();
    });

    it('uses new unit-test builder', () => {
      const builder = angular21Config.projects.ng21.architect.test.builder;
      expect(builder).toBe('@angular/build:unit-test');
    });

    it('has NO extract-i18n target', () => {
      const architect = angular21Config.projects.ng21.architect;
      expect((architect as Record<string, unknown>)['extract-i18n']).toBeUndefined();
    });

    it('ng add succeeds despite minimal config', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular21Config));

      const result = await ngAdd({ project: 'ng21' })(tree, {} as SchematicContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng21.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  /**
   * Cross-version compatibility summary
   */
  describe('Cross-version compatibility', () => {
    it('all versions have projectType: application', () => {
      expect(angular18Config.projects.ng18.projectType).toBe('application');
      expect(angular19Config.projects.ng19.projectType).toBe('application');
      expect(angular20Config.projects.ng20.projectType).toBe('application');
      expect(angular21Config.projects.ng21.projectType).toBe('application');
    });

    it('all versions have build target', () => {
      expect(angular18Config.projects.ng18.architect.build).toBeDefined();
      expect(angular19Config.projects.ng19.architect.build).toBeDefined();
      expect(angular20Config.projects.ng20.architect.build).toBeDefined();
      expect(angular21Config.projects.ng21.architect.build).toBeDefined();
    });

    it('outputPath evolution: string → string → undefined → undefined', () => {
      expect(typeof angular18Config.projects.ng18.architect.build.options.outputPath).toBe('string');
      expect(typeof angular19Config.projects.ng19.architect.build.options.outputPath).toBe('string');
      expect(angular20Config.projects.ng20.architect.build.options.outputPath).toBeUndefined();
      expect(angular21Config.projects.ng21.architect.build.options.outputPath).toBeUndefined();
    });

    it('builder evolution: @angular-devkit/build-angular → @angular/build', () => {
      expect(angular18Config.projects.ng18.architect.build.builder).toContain('@angular-devkit/build-angular');
      expect(angular19Config.projects.ng19.architect.build.builder).toContain('@angular-devkit/build-angular');
      expect(angular20Config.projects.ng20.architect.build.builder).toContain('@angular/build');
      expect(angular21Config.projects.ng21.architect.build.builder).toContain('@angular/build');
    });
  });
});
