/**
 * Angular Version Compatibility Tests
 *
 * These tests verify that angular-cli-ghpages correctly handles the angular.json
 * structure for each Angular version. The fixture files are actual angular.json
 * files generated by `ng new` with each Angular CLI version.
 *
 * Key difference relevant to us:
 * - Angular 18-19: outputPath is a string like "dist/<project>"
 * - Angular 20-21: outputPath is MISSING (uses default dist/<project>)
 */

import { SchematicContext, Tree } from '@angular-devkit/schematics';
import fs from 'fs';
import path from 'path';
import { ngAdd } from '../ng-add';

// Load fixture files - actual angular.json from each Angular CLI version
const fixturesDir = path.join(__dirname);
const angular18Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-18.json'), 'utf-8'));
const angular19Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-19.json'), 'utf-8'));
const angular20Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-20.json'), 'utf-8'));
const angular21Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-21.json'), 'utf-8'));

describe('Angular Version Compatibility', () => {
  describe('Angular 18', () => {
    it('has outputPath as string', () => {
      const outputPath = angular18Config.projects.ng18.architect.build.options.outputPath;
      expect(outputPath).toBe('dist/ng18');
    });

    it('ng add succeeds', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular18Config));

      const result = await ngAdd({ project: 'ng18' })(tree, {} as SchematicContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng18.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  describe('Angular 19', () => {
    it('has outputPath as string', () => {
      const outputPath = angular19Config.projects.ng19.architect.build.options.outputPath;
      expect(outputPath).toBe('dist/ng19');
    });

    it('ng add succeeds', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular19Config));

      const result = await ngAdd({ project: 'ng19' })(tree, {} as SchematicContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng19.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  describe('Angular 20', () => {
    it('has NO outputPath (uses default)', () => {
      const options = angular20Config.projects.ng20.architect.build.options;
      expect(options.outputPath).toBeUndefined();
    });

    it('ng add succeeds despite missing outputPath', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular20Config));

      const result = await ngAdd({ project: 'ng20' })(tree, {} as SchematicContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng20.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  describe('Angular 21', () => {
    it('has NO outputPath (uses default)', () => {
      const options = angular21Config.projects.ng21.architect.build.options;
      expect(options.outputPath).toBeUndefined();
    });

    it('ng add succeeds despite missing outputPath', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular21Config));

      const result = await ngAdd({ project: 'ng21' })(tree, {} as SchematicContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng21.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  describe('Cross-version compatibility', () => {
    it('all versions have projectType: application', () => {
      expect(angular18Config.projects.ng18.projectType).toBe('application');
      expect(angular19Config.projects.ng19.projectType).toBe('application');
      expect(angular20Config.projects.ng20.projectType).toBe('application');
      expect(angular21Config.projects.ng21.projectType).toBe('application');
    });

    it('all versions have build target', () => {
      expect(angular18Config.projects.ng18.architect.build).toBeDefined();
      expect(angular19Config.projects.ng19.architect.build).toBeDefined();
      expect(angular20Config.projects.ng20.architect.build).toBeDefined();
      expect(angular21Config.projects.ng21.architect.build).toBeDefined();
    });

    it('outputPath evolution: string → string → undefined → undefined', () => {
      expect(typeof angular18Config.projects.ng18.architect.build.options.outputPath).toBe('string');
      expect(typeof angular19Config.projects.ng19.architect.build.options.outputPath).toBe('string');
      expect(angular20Config.projects.ng20.architect.build.options.outputPath).toBeUndefined();
      expect(angular21Config.projects.ng21.architect.build.options.outputPath).toBeUndefined();
    });
  });
});
