/**
 * Angular Version Compatibility Tests
 *
 * These tests verify that angular-cli-ghpages correctly handles the angular.json
 * structure for each supported Angular version. The fixture files are actual
 * angular.json files generated by `ng new` with each Angular CLI version.
 *
 * outputPath is omitted in Angular 20+; the default is dist/<project>/browser.
 */

import { SchematicContext, Tree } from '@angular-devkit/schematics';
import fs from 'fs';
import path from 'path';
import { ngAdd } from '../ng-add';

// Mock context with logger - only the methods we actually use
const mockLogger = {
  info: jest.fn(),
  warn: jest.fn(),
  error: jest.fn(),
  debug: jest.fn(),
  fatal: jest.fn(),
  log: jest.fn(),
  createChild: jest.fn()
};

const mockContext = { logger: mockLogger } as unknown as SchematicContext;

// Load fixture files - actual angular.json from each Angular CLI version
const fixturesDir = path.join(__dirname);
const angular20Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-20.json'), 'utf-8'));
const angular21Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-21.json'), 'utf-8'));
const angular22Config = JSON.parse(fs.readFileSync(path.join(fixturesDir, 'angular-22.json'), 'utf-8'));

describe('Angular Version Compatibility', () => {
  describe('Angular 20', () => {
    it('has NO outputPath (uses default)', () => {
      const options = angular20Config.projects.ng20.architect.build.options;
      expect(options.outputPath).toBeUndefined();
    });

    it('ng add succeeds despite missing outputPath', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular20Config));

      const result = await ngAdd({ project: 'ng20' })(tree, mockContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng20.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  describe('Angular 21', () => {
    it('has NO outputPath (uses default)', () => {
      const options = angular21Config.projects.ng21.architect.build.options;
      expect(options.outputPath).toBeUndefined();
    });

    it('ng add succeeds despite missing outputPath', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular21Config));

      const result = await ngAdd({ project: 'ng21' })(tree, mockContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng21.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  describe('Angular 22', () => {
    it('has NO outputPath (uses default)', () => {
      const options = angular22Config.projects.ng22.architect.build.options;
      expect(options.outputPath).toBeUndefined();
    });

    it('ng add succeeds despite missing outputPath', async () => {
      const tree = Tree.empty();
      tree.create('angular.json', JSON.stringify(angular22Config));

      const result = await ngAdd({ project: 'ng22' })(tree, mockContext);
      const resultConfig = JSON.parse(result.read('angular.json')!.toString());

      expect(resultConfig.projects.ng22.architect.deploy.builder).toBe('angular-cli-ghpages:deploy');
    });
  });

  describe('Cross-version compatibility', () => {
    it('all versions have projectType: application', () => {
      expect(angular20Config.projects.ng20.projectType).toBe('application');
      expect(angular21Config.projects.ng21.projectType).toBe('application');
      expect(angular22Config.projects.ng22.projectType).toBe('application');
    });

    it('all versions have build target', () => {
      expect(angular20Config.projects.ng20.architect.build).toBeDefined();
      expect(angular21Config.projects.ng21.architect.build).toBeDefined();
      expect(angular22Config.projects.ng22.architect.build).toBeDefined();
    });

    it('outputPath is undefined for Angular 20+', () => {
      expect(angular20Config.projects.ng20.architect.build.options.outputPath).toBeUndefined();
      expect(angular21Config.projects.ng21.architect.build.options.outputPath).toBeUndefined();
      expect(angular22Config.projects.ng22.architect.build.options.outputPath).toBeUndefined();
    });
  });
});
