#!/usr/bin/env node

var path = require('path'),
  engine = require('./engine/engine'),
  defaults = require('./engine/defaults').defaults,
  pjson = require('./package.json'),
  commander = require('commander');

// defaults-file was ignored for --no-silent & --no-dotfiles, so it is not used here
// TODO: review https://github.com/tj/commander.js/issues/928 and check again if it now works
// (this is not a big problem, because true is currently the desired value and this is also the value in the defaults file)
commander
  .version(pjson.version)
  .description(pjson.description)
  .option(
    '-d, --dir <dir>',
    'Directory for all published sources, relative to the project-root.',
    defaults.dir
  )
  .option(
    '-r, --repo <repo>',
    'Provide the repository URL. If no value is provided, the `origin` remote of the current working directory is used.',
    defaults.repo
  )
  .option(
    '-m, --message <message>',
    'The commit message, must be wrapped in quotes.',
    defaults.message
  )
  .option(
    '-b, --branch <branch>',
    'The git branch to push your pages to.',
    defaults.branch
  )
  .option(
    '-n, --name <name>',
    'The git user-name which is associated with this commit.',
    defaults.name
  )
  .option(
    '-e, --email <email>',
    'The git user-email which is associated with this commit.',
    defaults.email
  )
  .option(
    '-S, --no-silent',
    'Logging is in silent mode by default. The option enables extended console logging. Keep this untouched if the repository URL or other information passed to git commands is sensitive!'
  )
  .option(
    '-T, --no-dotfiles',
    'Includes dotfiles by default. Otherwise files starting with `.` are ignored.'
  )
  .option(
    '-c, --cname <domain>',
    'Generate a CNAME file for the specified domain.',
    defaults.cname
  )
  .option(
    '--dry-run',
    'For testing: Run through without making any changes.',
    defaults.dryRun
  )
  .parse(process.argv);

var consoleLogger = {
  createChild: () => consoleLogger,
  log: console.log,
  debug: console.debug,
  info: console.info,
  warn: console.warn,
  error: console.error,
  fatal: console.error
};

var dir = path.join(process.cwd(), commander.dir);

engine.run(dir, commander, consoleLogger).catch(function(error) {
  consoleLogger.error('❌ An error occurred when trying to deploy:');
  consoleLogger.error(error.message);
  process.exit(1);
});
