/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Deployment of Angular CLI applications to GitHub pages (angular-cli-ghpages)
 */
export interface Schema {
  /**
   * Base url for the application being built. Same as `ng build --base-href=/XXX/`.
   */
  baseHref?: string;
  /**
   * A named build target, as specified in the `configurations` section of angular.json. Each named target is accompanied by a configuration of option defaults for that target. This is equivalent to calling the command `ng build --configuration=XXX`.
   */
  buildTarget?: string;
  /**
   * @deprecated
   * DEPRECATED: Use buildTarget instead. Legacy alias kept for backwards compatibility only.
   */
  browserTarget?: string;
  /**
   * Architect target for prerendering/SSG. Takes precedence over buildTarget when specified. Requires a prerender target configured in angular.json.
   */
  prerenderTarget?: string;
  /**
   * Skip build process during deployment.
   */
  noBuild?: boolean;
  /**
   * Provide the remote name. If no value is provided, `origin` is used. Has no function if --repo is set.
   */
  remote?: string;
  /**
   * Provide the repository URL. If no value is provided, a remote of the current working directory is used (defaults to `origin`; see --remote for details).
   */
  repo?: string;
  /**
   * The commit message.
   */
  message?: string;
  /**
   * The git branch to push your pages to.
   */
  branch?: string;
  /**
   * The git user-name which is associated with this commit.
   */
  name?: string;
  /**
   * The git user-email which is associated with this commit.
   */
  email?: string;
  /**
   * Deprecated! This parameter is no longer needed. It will be ignored.
   */
  noSilent?: boolean;
  /**
   * Exclude dotfiles (files starting with `.`) from deployment.
   */
  noDotfiles?: boolean;
  /**
   * By default a 404.html file is created for SPA routing on GitHub Pages. For Cloudflare Pages, you must use --no-notfound to enable native SPA routing.
   */
  noNotfound?: boolean;
  /**
   * Skip creating the .nojekyll file.
   */
  noNojekyll?: boolean;
  /**
   * Generate a CNAME file for the specified domain.
   */
  cname?: string;
  /**
   * Only add, and never remove existing files from the GitHub pages branch.
   */
  add?: boolean;
  /**
   * Overrides the directory for all published sources, relative to the current working directory.
   */
  dir?: string;
  /**
   * For testing: Run through without making any changes. Execute with --dry-run and nothing will happen.
   */
  dryRun?: boolean;
  [k: string]: unknown;
}
